/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inicio;

/**
 *
 * @author ANTONIO LEON
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        buscarID = new javax.swing.JMenuItem();
        buscarP = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        inC = new javax.swing.JMenuItem();
        inP = new javax.swing.JMenuItem();
        inCompra = new javax.swing.JMenuItem();
        inV = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        actClie = new javax.swing.JMenuItem();
        actP = new javax.swing.JMenuItem();
        actV = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        eliminarC = new javax.swing.JMenuItem();
        eliminarP = new javax.swing.JMenuItem();
        eliminarVenta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/t.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        jMenu1.setText("Buscar");

        buscarID.setText("Buscar ID");
        buscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarIDActionPerformed(evt);
            }
        });
        jMenu1.add(buscarID);

        buscarP.setText("Buscar Producto");
        buscarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPActionPerformed(evt);
            }
        });
        jMenu1.add(buscarP);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/insertar.png"))); // NOI18N
        jMenu2.setText("Insertar");

        inC.setText("Cliente");
        inC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inCActionPerformed(evt);
            }
        });
        jMenu2.add(inC);

        inP.setText("Producto");
        inP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inPActionPerformed(evt);
            }
        });
        jMenu2.add(inP);

        inCompra.setText("Compra de Producto");
        inCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inCompraActionPerformed(evt);
            }
        });
        jMenu2.add(inCompra);

        inV.setText("Insertar Venta");
        inV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inVActionPerformed(evt);
            }
        });
        jMenu2.add(inV);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizado.png"))); // NOI18N
        jMenu3.setText("Actualizar");

        actClie.setText("Cliente");
        actClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actClieActionPerformed(evt);
            }
        });
        jMenu3.add(actClie);

        actP.setText("Producto");
        actP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actPActionPerformed(evt);
            }
        });
        jMenu3.add(actP);

        actV.setText("Inventario");
        actV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actVActionPerformed(evt);
            }
        });
        jMenu3.add(actV);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar.png"))); // NOI18N
        jMenu4.setText("Eliminar");

        eliminarC.setText("Cliente");
        eliminarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCActionPerformed(evt);
            }
        });
        jMenu4.add(eliminarC);

        eliminarP.setText("Producto");
        eliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarPActionPerformed(evt);
            }
        });
        jMenu4.add(eliminarP);

        eliminarVenta.setText("Venta");
        eliminarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarVentaActionPerformed(evt);
            }
        });
        jMenu4.add(eliminarVenta);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarIDActionPerformed
        // TODO add your handling code here:
        buscarID b= new buscarID();
        b.setVisible(true);
    }//GEN-LAST:event_buscarIDActionPerformed

    private void buscarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPActionPerformed
        // TODO add your handling code here:
        buscarP p= new buscarP();
        p.setVisible(true);
    }//GEN-LAST:event_buscarPActionPerformed

    private void eliminarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCActionPerformed
        // TODO add your handling code here:
        eliminarC c= new eliminarC();
        c.setVisible(true);
            
    }//GEN-LAST:event_eliminarCActionPerformed

    private void eliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarPActionPerformed
        // TODO add your handling code here:
        eliminarP p= new eliminarP();
        p.setVisible(true);
    }//GEN-LAST:event_eliminarPActionPerformed

    private void eliminarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarVentaActionPerformed
        // TODO add your handling code here:
        eliminarVenta v= new eliminarVenta();
        v.setVisible(true);
    }//GEN-LAST:event_eliminarVentaActionPerformed

    private void inPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inPActionPerformed
        // TODO add your handling code here:
        inP i=new inP();
        i.setVisible(true);
    }//GEN-LAST:event_inPActionPerformed

    private void inCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inCActionPerformed
        // TODO add your handling code here:
        inC c= new inC();
        c.setVisible(true);
    }//GEN-LAST:event_inCActionPerformed

    private void inVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inVActionPerformed
        // TODO add your handling code here:
        inV v= new inV();
        v.setVisible(true);
    }//GEN-LAST:event_inVActionPerformed

    private void actClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actClieActionPerformed
        // TODO add your handling code here:
        actClie a=new actClie();
        a.setVisible(true);
    }//GEN-LAST:event_actClieActionPerformed

    private void actPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actPActionPerformed
        // TODO add your handling code here:
        actP p= new actP();
        p.setVisible(true);
    }//GEN-LAST:event_actPActionPerformed

    private void actVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actVActionPerformed
        // TODO add your handling code here:
        actV v=new actV();
        v.setVisible(true);
    }//GEN-LAST:event_actVActionPerformed

    private void inCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inCompraActionPerformed
        // TODO add your handling code here:
        inCompra c=new inCompra();
        c.setVisible(true);
    }//GEN-LAST:event_inCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public void vendedor(){
        buscarID.setEnabled(false);
        inC.setEnabled(false);
        inCompra.setEnabled(false);
        inP.setEnabled(false);
        actClie.setEnabled(false);
        eliminarC.setEnabled(false);
        eliminarP.setEnabled(false);
        eliminarVenta.setEnabled(false);
    }
    
    public void gerente(){
        buscarID.setEnabled(false);
        inC.setEnabled(false);
        actClie.setEnabled(false);
        eliminarC.setEnabled(false);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem actClie;
    private javax.swing.JMenuItem actP;
    private javax.swing.JMenuItem actV;
    private javax.swing.JMenuItem buscarID;
    private javax.swing.JMenuItem buscarP;
    private javax.swing.JMenuItem eliminarC;
    private javax.swing.JMenuItem eliminarP;
    private javax.swing.JMenuItem eliminarVenta;
    private javax.swing.JMenuItem inC;
    private javax.swing.JMenuItem inCompra;
    private javax.swing.JMenuItem inP;
    private javax.swing.JMenuItem inV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
